[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
  "python3.11 -m pip install --upgrade pip",
  "python3.11 -m pip install -r requirements.txt",
  "python3.11 -m playwright install-deps chromium",
  "python3.11 -m playwright install chromium"
]

[phases.start]
cmd = "python3.11 main.py"
