[phases.setup]
nixPkgs = ["python311Full"]

[phases.install]
cmds = [
  "python3 -m ensurepip --upgrade",
  "python3 -m pip install --upgrade pip",
  "python3 -m pip install -r requirements.txt",
  "python3 -m playwright install-deps chromium",
  "python3 -m playwright install chromium"
]

[phases.start]
cmd = "python3 main.py"
